baseURL = "/"
languageCode = "en-us"
title = "rougon"
[mediaTypes."text/netlify"]
delimiter = ""
suffix = ""
[outputFormats.players]
baseName = "players"
mediatype = "application/json"
[outputFormats.redirect]
baseName = "_redirects"
mediatype = "text/netlify"
[outputs]
home = ["json", "redirect"]
page = ["json", "players"]
section = ["json"]
taxonomy = ["json", "players"]
teams = ["json"]
[permalinks]
page = "/:section/:title/"
[taxonomies]
practice = "practices"
sport = "sports"
